### ISSUE TITLE
CAJ requires Java 8

### ISSUE THREAD

**Issue by jlmuir** [epics-base/caj#10]
In commit cb235bf1a46c91f82d2b0377912c165d8e86e072, CAJ was changed to require Java 8.  Does CAJ actually use Java 8 features?  If not, then it should not require Java 8.  CAJ used to only require J2SE 1.4.

**Comment by shroffk** [comment]
This is in preparation for exploring the 

1. Use of the new java.time which has nano second precision support.
2. Use of Functional interfaces for cleaning up the code.

The older released versions of caj, all still only require java 4.

The master branch/development branch which is currently for working towards the next release has been moved up to the current default version of java (which for both for openJDK and oracle's jdk is 8) - does this cause problems for your setup/use case?

**Comment by jlmuir** [comment]
> does this cause problems for your setup/use case?

No, that's fine.  I just wanted to make sure it wasn't an unnecessary requirement.  I support using new features available in newer versions of Java in newer versions of CAJ.  Thanks!
