### ISSUE TITLE
Where can I find the CAJ manual?

### ISSUE THREAD

**Issue by HongYi-Shern** [epics-base/caj#13]
The link is invalid. Where can I find the CAJ manual? If it is convenient, can you give me a copy?

Thank you.

**Comment by ralphlange** [comment]
Which link are you referring to?

Note that this repository is inactive = dead. (That's why it has been moved to the epics-rip organization.) The repository https://github.com/epics-base/jca contains the current code.

**Comment by HongYi-Shern** [comment]
OK,Thank you.
